"""rename address in Department

Revision ID: f405dec67b71
Revises: 49aa9ee9c171
Create Date: 2024-04-03 14:51:26.868084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f405dec67b71'
down_revision = '49aa9ee9c171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
